import { Footer } from "@/components/ui/Footer";
import { Header } from "@/components/ui/Header";
import classNames from "classnames";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: "normal",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Just Home",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      </head>
      <body className={classNames(roboto.className)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
